apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: ryeeshu/crm-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: SERVER_PORT
          value: "4000"
        - name: KAFKA_BROKERS
          value: "52.73.13.84:9092,100.51.187.149:9092,52.54.87.18:9092"
        - name: KAFKA_TOPIC
          value: "rdhurand.customer.evt"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "ryeeshudhurandhar@gmail.com"
        - name: SMTP_PASS
          value: "abif codj hjzm lgwp"
        - name: ANDREW_ID
          value: "rdhurand"
        # SMTP credentials would typically be in a Secret, but for A3 we use env or properties
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  selector:
    app: crm-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
