apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-bff
  template:
    metadata:
      labels:
        app: web-bff
    spec:
      containers:
      - name: web-bff
        image: ryeeshu/web-bff:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: SERVER_PORT
          value: "3000"
        - name: BOOK_SERVICE_URL
          value: "http://book-service"
        - name: CUSTOMER_SERVICE_URL
          value: "http://customer-service"
---
apiVersion: v1
kind: Service
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: web-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
